/*
---- WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING  ----
---- ANY MANUAL CHANGES IN THIS FILE WILL DISAPPEAR IF YOU REGENERATE ----
--------------------------------------------------------------------------
 This file has been generated by http://github.com/fnchooft/CStructGen
--------------------------------------------------------------------------
 Package: @PACKAGE_NAME@
 Version: @PACKAGE_VERSION@
 Sha1sum: b99c102ba284cc6d3b2a5174969f6a6dcef73dc8  Simple.h
--------------------------------------------------------------------------
 Make sure to update the originating Simple.h-file
--------------------------------------------------------------------------
---- WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING  ----
---- ANY MANUAL CHANGES IN THIS FILE WILL DISAPPEAR IF YOU REGENERATE ----
*/
#ifndef __DEFINITION_SIMPLE_H__
#define __DEFINITION_SIMPLE_H__


#include "Simple.h"


#ifdef __cplusplus


// C++ overloads, methods, and so on
#include <map>
#include <string>
#include <iostream>
#include <utility>
#include <sstream>
#include <stdint.h>


// Generated default toString,fromString,stream definitions for enumeration: AddDropType
std::string toString(AddDropType enumval, int32_t shortname = 0);
bool fromString(std::string stringvalue, AddDropType *enum_ptr);
std::ostream & operator<<(std::ostream & out, const AddDropType adddroptype);
// Generated toJsonString / fromJsonString definition for struct: AddDropType
std::string toJsonString(AddDropType *input);
int32_t fromJson(AddDropType *output, std::string jsondata);
// Generated stream-operators for: AddDrop
std::ostream & operator<<(std::ostream & out, const AddDrop & adddrop);
std::string toString(const AddDrop & adddrop);
// struct: AddDrop compare-functions due to union existance...
// Found Struct->settings.... 0
// Generated default compare definitions for struct: AddDrop
bool operator< (AddDrop lhs, AddDrop rhs);
bool operator<=(AddDrop lhs, AddDrop rhs);
bool operator> (AddDrop lhs, AddDrop rhs);
bool operator>=(AddDrop lhs, AddDrop rhs);
bool operator==(AddDrop lhs, AddDrop rhs);
bool operator!=(AddDrop lhs, AddDrop rhs);
// Generated toJsonString / fromJsonString definition for struct: AddDrop
std::string toJsonString(AddDrop *input);
int32_t fromJson(AddDrop *output, std::string jsondata);
// Generated stream-operators for: Simple
std::ostream & operator<<(std::ostream & out, const Simple & simple);
std::string toString(const Simple & simple);
// struct: Simple compare-functions due to union existance...
// Found Struct->settings.... 0
// Generated default compare definitions for struct: Simple
bool operator< (Simple lhs, Simple rhs);
bool operator<=(Simple lhs, Simple rhs);
bool operator> (Simple lhs, Simple rhs);
bool operator>=(Simple lhs, Simple rhs);
bool operator==(Simple lhs, Simple rhs);
bool operator!=(Simple lhs, Simple rhs);
// Generated toJsonString / fromJsonString definition for struct: Simple
std::string toJsonString(Simple *input);
int32_t fromJson(Simple *output, std::string jsondata);
// Generated stream-operators for: SOspfInterface
std::ostream & operator<<(std::ostream & out, const SOspfInterface & sospfinterface);
std::string toString(const SOspfInterface & sospfinterface);
// struct: SOspfInterface compare-functions due to union existance...
// Found Struct->settings.... 0
// Generated default compare definitions for struct: SOspfInterface
bool operator< (SOspfInterface lhs, SOspfInterface rhs);
bool operator<=(SOspfInterface lhs, SOspfInterface rhs);
bool operator> (SOspfInterface lhs, SOspfInterface rhs);
bool operator>=(SOspfInterface lhs, SOspfInterface rhs);
bool operator==(SOspfInterface lhs, SOspfInterface rhs);
bool operator!=(SOspfInterface lhs, SOspfInterface rhs);
// Generated toJsonString / fromJsonString definition for struct: SOspfInterface
std::string toJsonString(SOspfInterface *input);
int32_t fromJson(SOspfInterface *output, std::string jsondata);
// Generated stream-operators for: SOspfNeighbor
std::ostream & operator<<(std::ostream & out, const SOspfNeighbor & sospfneighbor);
std::string toString(const SOspfNeighbor & sospfneighbor);
// struct: SOspfNeighbor compare-functions due to union existance...
// Found Struct->settings.... 0
// Generated default compare definitions for struct: SOspfNeighbor
bool operator< (SOspfNeighbor lhs, SOspfNeighbor rhs);
bool operator<=(SOspfNeighbor lhs, SOspfNeighbor rhs);
bool operator> (SOspfNeighbor lhs, SOspfNeighbor rhs);
bool operator>=(SOspfNeighbor lhs, SOspfNeighbor rhs);
bool operator==(SOspfNeighbor lhs, SOspfNeighbor rhs);
bool operator!=(SOspfNeighbor lhs, SOspfNeighbor rhs);
// Generated toJsonString / fromJsonString definition for struct: SOspfNeighbor
std::string toJsonString(SOspfNeighbor *input);
int32_t fromJson(SOspfNeighbor *output, std::string jsondata);
// Generated stream-operators for: SOspf
std::ostream & operator<<(std::ostream & out, const SOspf & sospf);
std::string toString(const SOspf & sospf);
// struct: SOspf compare-functions due to union existance...
// Found Struct->settings.... 0
// Generated default compare definitions for struct: SOspf
bool operator< (SOspf lhs, SOspf rhs);
bool operator<=(SOspf lhs, SOspf rhs);
bool operator> (SOspf lhs, SOspf rhs);
bool operator>=(SOspf lhs, SOspf rhs);
bool operator==(SOspf lhs, SOspf rhs);
bool operator!=(SOspf lhs, SOspf rhs);
// Generated toJsonString / fromJsonString definition for struct: SOspf
std::string toJsonString(SOspf *input);
int32_t fromJson(SOspf *output, std::string jsondata);
#endif // ___cplusplus


#endif // __DEFINITION_SIMPLE_H__
